### ISSUE TITLE
What is the mechanical method of connection for the switches?

### ISSUE THREAD

**Issue by JellyTitan** [girishji/optical-amoeba#1]
For other Amoeba variants, soldering or hotswap sockets are used to keep the mechanical switches in place. Do the optical switches fit tightly enough into the optical amoeba pcbs to keep them from slipping off if they were in something like a dactyl manuform?

**Comment by girishji** [comment]
No, there is some play in the hole where switch sits. Making that hole tighter will interfere with the functioning, and it will not hold the switch anyway (hole is too small compared to size of the switch). 
If you are 3D printing the case, you can make the square hole a little smaller than 14x14 so you can have a really snug fit.
Even better would be to design the whole pcb, have it made with a semi-flexible pcb material (0.6mm), have smd components soldered (all by jlcpcb for instance). You just have to solder a MCU on to it.
See:
https://girishji.github.io/opticalkb/2022/08/17/optical-keyboard-design.html
https://github.com/girishji/optical-keyboard
https://github.com/girishji/optical-keyboard-mx
https://girishji.github.io/kicad/2022/08/17/kicad-python-footprints-curved-tracks-edge-cuts.html

**Comment by JellyTitan** [comment]
Thanks! This is exactly what i was looking for!
